FROM java:8-jre-alpine


ENV SPRING_CLOUD_CONSUL_HOST consul
ENV UBOX_DATABASE_HOST ubox_db
ENV UBOX_DATABASE_USER postgres
ENV UBOX_DATABASE_PASSWORD postgres
ENV UBOX_DATABASE_NAME postgres
ENV UBOX_DATABASE_PORT 5432

EXPOSE 8080

ADD build/libs/ubox-0.0.1-SNAPSHOT.jar /app.jar

CMD java -jar /app.jar